import sys
import json
from pathlib import Path

# Add parent directory to python path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import engine, SessionLocal
from app.models import Document, ThirdPartyApplication, CallbackRule
from app.services.callback_service import (
    execute_sp_for_callback_payload,
    build_callback_request,
    build_document_context
)
from sqlalchemy import text

def run_test():
    print("==========================================================================")
    print(" TESTING SQL STORED PROCEDURE DYNAMIC PAYLOAD CALLBACK ENGINE")
    print("==========================================================================")
    
    # 1. Ensure Stored Procedure exists in MS SQL Server
    try:
        sp_sql = open('backend/sql/sp_GetApprovalCallbackPayload.sql').read()
        with engine.connect() as conn:
            for stmt in sp_sql.split('GO'):
                if stmt.strip():
                    conn.execute(text(stmt))
        print("[SQL Prep] Ensured sp_GetApprovalCallbackPayload procedure exists in SQL Server.")
    except Exception as e:
        print(f"[SQL Prep Notice] {e}")

    db = SessionLocal()
    try:
        # 2. Fetch test document
        doc = db.query(Document).filter(Document.is_deleted == False).first()
        if not doc:
            print("[TEST FAIL] No document found in database")
            return
            
        print(f"[TEST] Using Document: ID='{doc.id}', DocKey='{doc.doc_key}', Amount={doc.amount}")
        
        # 3. Test Stored Procedure Payload Execution directly
        doc_ctx = build_document_context(doc, decision="APPROVED")
        payload_str = execute_sp_for_callback_payload(db, "sp_GetApprovalCallbackPayload", doc.id, doc_ctx)
        
        print("\n[TEST RESULT] Dynamic Payload Generated by SP Engine:")
        print(payload_str)
        
        payload_json = json.loads(payload_str)
        assert "documentId" in payload_json or "docKey" in payload_json or "externalDocKey" in payload_json
        print("\n[TEST SUCCESS] JSON Schema validated successfully!")

        # 4. Test Full Request Builder with SQL_PROCEDURE rule
        rule = CallbackRule(
            rule_name="Dynamic SP Payload Test Rule",
            payload_source="SQL_PROCEDURE",
            stored_procedure_name="sp_GetApprovalCallbackPayload",
            http_method="POST",
            body_type="SQL_PROCEDURE",
            url_mode="OVERRIDE",
            custom_url="https://api.erp-integration.local/v1/approval"
        )
        app = ThirdPartyApplication(
            name="Test Enterprise Application",
            code="ERP_TEST",
            base_url="https://api.erp-integration.local"
        )
        
        method, url, headers, body = build_callback_request(rule, app, doc_ctx, db=db)
        print(f"\n[TEST SUCCESS] Built Outbound Request:")
        print(f"  Method: {method}")
        print(f"  URL: {url}")
        print(f"  Content-Type: {headers.get('Content-Type')}")
        print(f"  HMAC Signature Header: {headers.get('X-Approval-Signature')}")
        print(f"  Body Preview (First 200 chars): {body.decode('utf-8')[:200]}...")

    finally:
        db.close()

if __name__ == "__main__":
    run_test()
